schema_version: 1

system:
  crystal: "diamond"
  crystal_file_path: null
  spin: 0
  spin_restricted: false

method:
  xc: "lda_x+lda_c_pw"
  family: "nc"
  pseudopotential_file_dir: "/home/aiops/litb/projects/jrystal/pseudopotential/normconserving/"
  # pseudopotential_file_dir: "/home/aiops/litb/projects/jrystal/pseudopotential/ultrasoft/"

basis:
  freq_mask_method: "spherical"
  cutoff_energy: 10
  grid_sizes: 24

ksampling:
  k_grid_sizes: [1, 1, 1]
  symmetry_reduction: true

solver:
  mode: "auto"
  auto:
    primary: "scf"
    fallback: "direct_opt"
    fallback_on_nonconverged: true
    fallback_on_error: true
  scf:
    max_iter: 100
    eigensolver:
      method: "lobpcg"
      max_iter: 6
    mixing:
      method: "diis"
      beta: 0.8
      history_size: 8
    convergence:
      density_tol: 1.0e-3
      energy_tol: 1.0e-7
  direct_opt:
    max_steps: 20000
    optimizer:
      name: "adam"
      learning_rate: 0.1
      b1: 0.9
      b2: 0.99
    scheduler: null
    occupation_optimizer:
      warmup_steps: 2000
      learning_rate: 0.01
      scheduler: null
      # scheduler:
      #   name: "reduce_on_plateau"
      #   factor: 0.5
      #   patience: 50
      #   rtol: 1.0e-4
      #   atol: 0.0
      #   cooldown: 20
      #   accumulation_size: 1
      #   min_scale: 1.0e-2
    convergence:
      window_size: 20
      energy_std_tol: 1.0e-7

occupation:
  method: "fermi-dirac"
  # method: "fixed"
  smearing: 0.001
  empty_bands: 10

ewald:
  eta: 0.1
  cutoff: 2.0e+4

band:
  empty_bands: 10
  k_path_special_points: "LGXL"
  num_kpoints: 64
  k_path_file: null
  epoch: 5000
  fine_tuning: true
  fine_tuning_epoch: 300
  plot:
    enabled: true
    unit: "eV"
    y_min: -20
    y_max: 20

execution:
  seed: 123
  parallel_over_k_mesh: false
  parallel_over_k_path: true
  profile: false
  xla_preallocate: true
  jax_enable_x64: true
  jax_debug_nans: false
  verbose: true
  eps: 1.0e-8

experimental:
  disable_jit: false

io:
  output_dir: "out/"
  save_dir: null
  run_label: null
  save_density: true
  save_wavefunction: false
  save_ground_state_spectrum: false
  save_checkpoint: false
  checkpoint_interval: 10000
  restart: "from_scratch"
  log_level: "normal"
