schema_version: 1

system:
  crystal: "diamond"
  crystal_file_path: null
  spin: 0
  spin_restricted: true

method:
  xc: "lda_x"
  use_pseudopotential: false
  pseudopotential_type: "nc"
  pseudopotential_file_dir: "/home/aiops/litb/projects/jrystal/pseudopotential/normconserving/"

basis:
  freq_mask_method: "spherical"
  cutoff_energy: 100
  grid_sizes: 48

ksampling:
  k_grid_sizes: [1, 1, 1]
  symmetry_reduction: true

solver:
  mode: "auto"
  auto:
    primary: "scf"
    fallback: "direct_opt"
    fallback_on_nonconverged: true
    fallback_on_error: true
  scf:
    max_iter: 100
    eigensolver:
      method: "lobpcg"
      max_iter: 6
    mixing:
      method: "diis"
      beta: 0.8
      history_size: 8
    convergence:
      density_tol: 1.0e-3
      energy_tol: 1.0e-8
  direct_opt:
    max_steps: 20000
    optimizer:
      name: "adam"
      learning_rate: 1
      b1: 0.9
      b2: 0.99
    scheduler: null
    convergence:
      window_size: 20
      energy_std_tol: 1.0e-8

occupation:
  # method: "fermi-dirac"
  method: "fixed"
  smearing: 0.001
  empty_bands: 20
  warmup_steps: 2000

ewald:
  eta: 0.1
  cutoff: 2.0e+4

band:
  empty_bands: null
  k_path_special_points: "LGXL"
  num_kpoints: 64
  k_path_file: null
  epoch: 5000
  fine_tuning: true
  fine_tuning_epoch: 300

execution:
  seed: 123
  parallel_over_k_mesh: false
  parallel_over_k_path: true
  xla_preallocate: true
  jax_enable_x64: true
  jax_debug_nans: false
  verbose: true
  eps: 1.0e-8

io:
  save_dir: null
