[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "jrystal"
version = "0.0.2"
description = "A JAX-based Differentiable DFT Framework for Materials"
authors = [{ name = "Tianbo Li", email = "li_tianbo@live.com" }]
license = { file = "LICENSE" }
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.11"
dependencies = [
  "jax[cuda]>=0.8.0",
  "jaxlib>=0.8.0",
  "optax>=0.2.0",
  "jaxtyping",
  "tqdm",
  "ase",
  "absl-py",
  "einops",
  "ml_collections",
  "interpax",
  "chex",
  "jxc-python>=0.1.12",
  "spglib>=2.0.0",
]
keywords = [
  "jax",
  "density functional theory",
  "materials science",
  "GPU",
  "plane wave",
]
classifiers = [
  'Environment :: Console',
  'Intended Audience :: Science/Research',
  'Intended Audience :: Developers',
  'License :: OSI Approved :: Apache License 2.0',
  'Programming Language :: Python',
  'Programming Language :: Python :: 3',
  'Topic :: Software Development :: Libraries :: Python Modules',
  'Topic :: Scientific/Engineering',
]


[project.urls]
"Homepage" = "https://github.com/sail-sg/jrystal"
"Documentation" = "https://sail-sg.github.io/jrystal/"
"Source" = "https://github.com/sail-sg/jrystal"
"Tracker" = "https://github.com/sail-sg/jrystal/issues"
"Repository" = "https://github.com/sail-sg/jrystal"


[project.optional-dependencies]
dev = ["mypy>=1.5.0", "yapf", "pylint", "isort", "flake8"]
format = ["yapf"]
lint = ["pylint"]
docs = ["sphinx>=7.0.0", "sphinx-rtd-theme>=1.0.0"]


[project.scripts]
jrystal = "main:main"


[tool.setuptools.packages.find]
include = ["jrystal*"]


[tool.yapf]
based_on_style = "google"
indent_width = 2
spaces_before_comment = 2
dedent_closing_brackets = true
column_limit = 80
continuation_indent_width = 2
split_all_top_level_comma_separated_values = true


[tool.pylint.messages_control]
disable = [
  "C0103", # Invalid name
  "C0301", # Too many lines in module
  "C0302", # Too many lines in class
  "W0702", # No exception
  "W1401", # Too many statements
  "E0602", # Undefined name
  "E0601", # Undefined name
  "R0903", # Too few public methods
  "R0913", # Too many arguments
  "R0914", # Too many local variables
  # "W0311", # Bad indentation
]


[tool.pylint.format]
indent-string = "  "
max-line-length = 80


[tool.flake8]
max-line-length = 80
indent-size = 2
extend-ignore = [
  "F722",
  "W293",
  "W291",
  "E731",
  "E124",
  "W605",
  "E722",
  "F821",
  "E111",
  "E114",
]
